run:
  skip-dirs:
    - docs
    - gen
linters:
  enable:
    - revive
    - lll
issues:
  exclude-rules:
    - linters:
        - lll
      source: '^//\+kubebuilder'
    - linters:
        - revive
      text: "empty-block: this block is empty, you can remove it"
