contexts:
    - name: local
      service: local
      user: local
      project_id: hej
      environment_id: prod
services:
    - name: local
      server: http://localhost:4748
users:
    - name: local
      auth:
        user_id: c43941c9-a3f0-448b-9f62-890a28b65830
        access_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJncHMiOlsiYWRtaW4iXSwic3ViIjoiYzQzOTQxYzktYTNmMC00NDhiLTlmNjItODkwYTI4YjY1ODMwIiwic3R5IjoxLCJqdGkiOiJiYzE3ZDU0ZC00Mjg3LTRkNTQtYTA2My1jM2EzMDYwNDYxNjEiLCJleHAiOjE3MDU3NjAzMzIsImlhdCI6MTcwNTc1NjczMn0.BwgcGoKl-BO3Vf4SzSLCEN2HHimCPdsslB8u1CfdJmFaLljE4dIzOlWWoUeheXNxbUVwiEZy8STN1kwGfQBuXQ
        refresh_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJncHMiOlsiYWRtaW4iXSwic3ViIjoiYzQzOTQxYzktYTNmMC00NDhiLTlmNjItODkwYTI4YjY1ODMwIiwic3R5IjoxLCJqdGkiOiJiYzE3ZDU0ZC00Mjg3LTRkNTQtYTA2My1jM2EzMDYwNDYxNjEiLCJleHAiOjE3MDYzNjE1MzIsImlhdCI6MTcwNTc1NjczMn0.AKaov8vH3lcHkTxS-NQh0bUcSqZLaArpC3Es98kZNlpg0XR4-6x-8YuzEHP3YzNEvr6KkyYZrJTWFLWcuOnTQA
current_context: local
