{{- if .Values.mongodb.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rig-platform.fullname" . }}-mongodb
  labels: {{ include "rig-platform.mongodb.labels" . | nindent 4 }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ "mongodb" | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ "mongodb" | b64enc }}
  MONGO_INITDB_DATABASE: {{ "rig" | b64enc }}
{{- end -}}
