{{- if .Values.rbac.platform.create_token -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.platform.service_account }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.platform.service_account }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.platform.service_account }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
