{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rig-operator.fullname" . }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "rig-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "rig-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
