apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rig-operator.fullname" . }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "rig-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "rig-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rig-operator.serviceAccountName" . }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- if .Values.config.webhooksEnabled }}
            - name: webhooks
              containerPort: 9443
              protocol: TCP
            {{- end }}
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/rig-operator
            {{- if .Values.config.webhooksEnabled }}
            - name: webhook-cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "rig-operator.secretName" . }}
        {{- if .Values.config.webhooksEnabled }}
        - name: webhook-cert
          secret:
            defaultMode: 420
            secretName: {{ include "rig-operator.fullname" . }}-webhook-tls
        {{- end }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
