{{- if not .Values.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rig-operator.fullname" . }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "rig-operator.config" . | b64enc }}
{{- end -}}
