{{- if .Values.rbac.platform.create_token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rbac.platform.service_account }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.rbac.platform.service_account }}
type: kubernetes.io/service-account-token
{{- end -}}
