{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rig-operator.serviceAccountName" . }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
{{- end }}
