{{- if .Values.rbac.platform.create_token -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.platform.service_account }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
{{- end }}
