{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rig.fullname" . }}
  labels: {{ include "rig.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - configmaps
    - secrets
    - namespaces
    - pods/log
  verbs:
    - "*"
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - "*"
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - "*"
- apiGroups:
    - metrics.k8s.io
  resources:
    - pods
  verbs:
    - list
- apiGroups:
    - rig.dev
  resources:
    - capsules
  verbs:
    - "*"

{{- end -}}
