{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rig.fullname" . }}-leader-election
  labels: {{ include "rig.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "rig.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "rig.fullname" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
