apiVersion: v1
kind: Service
metadata:
  name: {{ include "rig.fullname" . }}-svc
  labels: {{ include "rig.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }} 
      {{- end }}
      protocol: TCP
    {{- if .Values.webhooks.enabled }}
    - name: webhooks
      port: 9443
      targetPort: webhooks
      protocol: TCP
    {{- end }}
  selector: {{ include "rig.selectorLabels" . | nindent 4 }}
