name: "Run Integration Tests"
inputs:
  platform-path:
    default: "."
runs:
  using: "composite"
  steps:
    - name: Rig kind setup
      run: |
        cd ${{ inputs.platform-path }}
        ./tests/integration/init.sh

    - name: Test
      env:
        RUN_INTEGRATION_TEST: true
      run: |
        cd ${{ inputs.platform-path }}
        task test-integration

    - name: Upload test output
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-integration
        path: ${{ inputs.platform-path }}/output/test-integration

    - name: Platform Output
      if: always()
      run: kubectl logs -n rig-system deploy/rig-platform

    - name: Operator Output
      if: always()
      run: kubectl logs -n rig-system deploy/rig-operator

    - name: Kubectl Output
      if: always()
      run: kubectl get all,capsule -A
