name: Main docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/package/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/rigdev/rig-operator:main
