name: Main docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docs
          file: ./build/package/docs.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/rigdev/docs:latest
            ghcr.io/rigdev/docs:${{ github.sha }}

      - name: Setup rig
        uses: rigdev/setup-rig@v1
        with:
          host: ${{ vars.RIG_HOST }}
          client-id: ${{ vars.RIG_CLIENT_ID }}
          client-secret: ${{ secrets.RIG_CLIENT_SECRET }}

      - name: Deploy
        run: |
          rig deploy docs \
            --project docs \
            --environment production \
            --image ghcr.io/rigdev/docs:${{ github.sha }}
