name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue is stale because it has been waiting for more information for 30 days with no activity. Remove stale label or comment or this will be closed in 7 days. If the issue has been clarified, remove the needs-more-info label."
          stale-pr-message: "This pr is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days."
          any-of-issue-labels: needs-more-info
