apiVersion: v1
kind: ConfigMap
metadata:
  name: rig-platform
data:
  {{- if .Values.postgres.enabled }}
  RIG_CLIENT_POSTGRES_HOST: rig-platform-postgres:5432
  {{- end }}
  {{- if .Values.mongodb.enabled }}
  RIG_CLIENT_MONGO_HOST: rig-platform-mongodb:27017
  {{- end }}
