apiVersion: v1
kind: Service
metadata:
  name: {{ include "rig-platform.fullname" . }}-svc
  labels: {{ include "rig-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector: {{ include "rig-platform.selectorLabels" . | nindent 4 }}
