{{- if .Values.loadBalancer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: rig-platform-load-balancer
spec:
  type: NodePort
  selector:
    rig.dev/capsule: rig-platform
  ports:
  - name: http
    port: {{ .Values.port }}
    nodePort: {{ .Values.loadBalancer.nodePort }}
    targetPort: http
{{- end }}
